import type { Metadata } from "next";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import NextTopLoader from "nextjs-toploader";
import { Toaster as SonnerToaster } from "sonner";

import { auth } from "@/auth";
import { Footer } from "@/components/shared/footer/footer";
import { Toaster } from "@/components/ui/toaster";
import { CurrentUserProvider } from "@/context/current-user-provider";
import { cn } from "@/lib/utils";

import { montserrat, tradeGothic, tradeGothicExtended } from "./fonts";

export const metadata: Metadata = {
  title: "Golobe",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body
          className={cn(
            montserrat.variable,
            tradeGothicExtended.variable,
            tradeGothic.variable,
            "font-mont"
          )}
        >
          <Toaster />
          <SonnerToaster />
          <NextTopLoader />
          <CurrentUserProvider>{children}</CurrentUserProvider>
          <Footer />
        </body>
      </html>
    </SessionProvider>
  );
}
