import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { montserrat, tradeGothic, tradeGothicExtended } from "./fonts";
import { Footer } from "@/components/shared/footer/footer";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "@/components/ui/toaster";
import { Toaster as SonnerToaster } from "sonner";

export const metadata: Metadata = {
  title: "Golobe",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body
          className={cn(
            montserrat.variable,
            tradeGothicExtended.variable,
            tradeGothic.variable,
            "font-mont"
          )}
        >
          <Toaster />
          <SonnerToaster />
          <NextTopLoader />

          {children}
          <Footer />
        </body>
      </html>
    </SessionProvider>
  );
}
